on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  
jobs:
  ApprovalJob:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Approval
    steps:
      - run: echo Hello from Approval environment
  
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Sleep X Seconds
        run: sleep 22
      
      - name: Complete
        run: echo run Complete

  ApprovalJob2:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Approval
    steps:
      - run: echo Goodbye from Approval environment
