on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.run_id }}
      
      - name: Sleep X Seconds
        run: sleep 25
      
      - name: Complete
        run: echo run Complete

  ApprovalJob:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ TestJob ]
    environment: Approval
    steps:
      - run: echo Goodbye from Approval environment

  TestJob2:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ ApprovalJob ]
    steps:
      - uses: actions/checkout@v3
      
      - name: Sleep X Seconds
        run: sleep 25
      
      - name: Complete
        run: echo run Complete
